pipeline {
   agent {
       label 'agent1'
   }

   stages {
      stage('Hello') {
         steps {
                sh 'java -version'
                echo "Get working directory"
                sh 'pwd'
         }
      }
   }
}
